//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dose_Profile
    {
        public int ID { get; set; }
        public Nullable<int> ID_Profile { get; set; }
        public Nullable<int> ID_Type_Coefficient { get; set; }
        public Nullable<System.TimeSpan> Time_Begin { get; set; }
        public Nullable<System.TimeSpan> Time_End { get; set; }
        public Nullable<float> Coefficient { get; set; }
    
        public virtual Type_Coefficient Type_Coefficient { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
