//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiabetDBEntities1 : DbContext
    {
        public DiabetDBEntities1()
            : base("name=DiabetDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diary_Line> Diary_Line { get; set; }
        public virtual DbSet<Diary_Product> Diary_Product { get; set; }
        public virtual DbSet<Dose_Profile> Dose_Profile { get; set; }
        public virtual DbSet<GeneralDiary_Person> GeneralDiary_Person { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Type_Coefficient> Type_Coefficient { get; set; }
        public virtual DbSet<Type_Product> Type_Product { get; set; }
    }
}
