//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Diary_Product = new HashSet<Diary_Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<float> Glycemic_Index { get; set; }
        public Nullable<float> Calories { get; set; }
        public Nullable<float> Protein { get; set; }
        public Nullable<float> Fats { get; set; }
        public Nullable<float> Carbohydrates { get; set; }
        public Nullable<int> ID_Type_Product { get; set; }

        public string ColorIndex
        {
            get
            {
                if (Glycemic_Index >= 70)
                {
                    return "#FF1F1F";
                }
                else if (Glycemic_Index <= 69 && Glycemic_Index >= 50)
                {
                    return "#e8fc05";
                }
                else
                {
                    return "#05fc0d";
                }
            }
        }
        public string ColorText
        {
            get
            {
                if (ColorIndex == "#FF1F1F")
                {
                    return "#fafcfa";
                }
                else
                {
                    return "#030303";
                }
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diary_Product> Diary_Product { get; set; }
        public virtual Type_Product Type_Product { get; set; }
    }
}
